// <auto-generated />
using System;
using BlazorServer.BuilderPatternExample.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServer.BuilderPatternExample.Migrations
{
    [DbContext(typeof(BuilderPatternExampleContext))]
    partial class BuilderPatternExampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("BlazorServer.BuilderPatternExample.Domain.Models.Cpu", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseSpeed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Cores")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cost")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cpus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSpeed = "1.5gHz",
                            Cores = 4,
                            Cost = 100,
                            Description = "Intel i5",
                            Name = "Intel i5",
                            Slug = "BASE"
                        },
                        new
                        {
                            Id = 2,
                            BaseSpeed = "2.2gHz",
                            Cores = 10,
                            Cost = 250,
                            Description = "Intel i7",
                            Name = "Intel i7",
                            Slug = "MID"
                        },
                        new
                        {
                            Id = 3,
                            BaseSpeed = "3gHz",
                            Cores = 20,
                            Cost = 500,
                            Description = "Intel i9",
                            Name = "Intel i9",
                            Slug = "TOP"
                        });
                });

            modelBuilder.Entity("BlazorServer.BuilderPatternExample.Domain.Models.CustomPc", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CpuId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GpuId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HardDriveId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PcLevelId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RamId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalCost")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CpuId");

                    b.HasIndex("GpuId");

                    b.HasIndex("HardDriveId");

                    b.HasIndex("PcLevelId");

                    b.HasIndex("RamId");

                    b.ToTable("CustomPcs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CpuId = 3,
                            CustomerName = "Fletcher",
                            Description = "Fletche Top Pc",
                            GpuId = 3,
                            HardDriveId = 3,
                            Name = "Fletcher Top Pc",
                            PcLevelId = 3,
                            RamId = 3,
                            Slug = "None",
                            TotalCost = 1675
                        });
                });

            modelBuilder.Entity("BlazorServer.BuilderPatternExample.Domain.Models.Gpu", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cost")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gpus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 300,
                            Description = "NVIDIA GeForce RTX 2070",
                            Name = "NVIDIA GeForce RTX 2070",
                            Slug = "BASE"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 500,
                            Description = "NVIDIA GeForce RTX 3070",
                            Name = "NVIDIA GeForce RTX 3070",
                            Slug = "MID"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 800,
                            Description = "NVIDIA GeForce RTX 4070",
                            Name = "NVIDIA GeForce RTX 4070",
                            Slug = "TOP"
                        });
                });

            modelBuilder.Entity("BlazorServer.BuilderPatternExample.Domain.Models.HardDrive", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cost")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Size")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HardDrives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 50,
                            Description = "256GB SSD",
                            Name = "256GB SSD",
                            Size = 256,
                            Slug = "BASE",
                            Type = "SSD"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 100,
                            Description = "512GB SSD",
                            Name = "512GB SSD",
                            Size = 512,
                            Slug = "MID",
                            Type = "SSD"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 200,
                            Description = "1024GB SSD",
                            Name = "1024GB SSD",
                            Size = 1024,
                            Slug = "TOP",
                            Type = "SSD"
                        });
                });

            modelBuilder.Entity("BlazorServer.BuilderPatternExample.Domain.Models.PcLevel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PcLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Base Model",
                            Name = "Base Model",
                            Slug = "BASE"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mid Model",
                            Name = "Mid Model",
                            Slug = "MID"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Top Model",
                            Name = "Top Model",
                            Slug = "TOP"
                        });
                });

            modelBuilder.Entity("BlazorServer.BuilderPatternExample.Domain.Models.Ram", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cost")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RamAmount")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 50,
                            Description = "8GB DDR5",
                            Name = "8GB DDR5",
                            RamAmount = 8,
                            Slug = "BASE",
                            Type = "DDR5"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 100,
                            Description = "16GB DDR5",
                            Name = "16GB DDR5",
                            RamAmount = 16,
                            Slug = "MID",
                            Type = "DDR5"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 175,
                            Description = "32GB DDR5",
                            Name = "32GB DDR5",
                            RamAmount = 32,
                            Slug = "TOP",
                            Type = "DDR5"
                        });
                });

            modelBuilder.Entity("BlazorServer.BuilderPatternExample.Domain.Models.CustomPc", b =>
                {
                    b.HasOne("BlazorServer.BuilderPatternExample.Domain.Models.Cpu", "Cpu")
                        .WithMany()
                        .HasForeignKey("CpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorServer.BuilderPatternExample.Domain.Models.Gpu", "Gpu")
                        .WithMany()
                        .HasForeignKey("GpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorServer.BuilderPatternExample.Domain.Models.HardDrive", "HardDrive")
                        .WithMany()
                        .HasForeignKey("HardDriveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorServer.BuilderPatternExample.Domain.Models.PcLevel", "PcLevel")
                        .WithMany()
                        .HasForeignKey("PcLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorServer.BuilderPatternExample.Domain.Models.Ram", "Ram")
                        .WithMany()
                        .HasForeignKey("RamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cpu");

                    b.Navigation("Gpu");

                    b.Navigation("HardDrive");

                    b.Navigation("PcLevel");

                    b.Navigation("Ram");
                });
#pragma warning restore 612, 618
        }
    }
}
